baseURL = "https://maggioni.dev/"
theme = "PaperMod"

[pagination]
pagerSize = 10

[services]
  [services.disqus]
    shortname = 'maggionidev'
  [services.googleAnalytics]
    id = 'G-3EJS7QXCTZ'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

defaultContentLanguage = "pt-BR"
defaultContentLanguageInSubdir = true

[languages]
[languages.pt-BR]
  languageCode = "pt-BR"
  languageName = "Português (Brasil)"

  weight = 1 
  title = "Gabriel Maggioni" 

  [languages.pt-BR.params]
    description = "Programação, Blender, Unity e DevLogs..."

    [languages.pt-BR.params.homeInfoParams]
      Title = "Olá! 👋"
      Content = "Bem vindo ao meu blog!"


enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  keywords = ["programação", "desenvolvimento de software", "desenvolvimento de jogos", "unity", "blender", "gamedev", "devlog", "projetos pessoais", "tecnologia", "programming", "software development", "game development", "coding", "3d modeling", "indie dev"]
  author = "Gabriel Maggioni"
  DateFormat = "02 Jan 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  comments = true
  images = ["og-image.png"]

  ShowReadingTime = true
  ShowShareButtons = true
  ShareButtons = ["whatsapp", "x", "reddit", "telegram", "linkedin"]

  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

  [params.label]
    text = "Home"
    icon = "/apple-touch-icon.png"
    iconHeight = 45

  [params.profileMode]
    enabled = true
    title = "Gabriel Maggioni"
    subtitle = "Olá 👋 aqui falo sobre Unity, Blender e Código!"
    imageUrl = "/apple-touch-icon.png"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"

    [[params.profileMode.buttons]]
      name = "Ver Posts"
      url = "posts"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://youtube.com/@maggionidev"
  [[params.socialIcons]]
    name = "tiktok"
    url = "https://tiktok.com/@maggionidev"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/maggionidev"
  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/maggionidev"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/maggionidev"

# [params.analytics.google]
#    SiteVerificationTag = "XYZabc"
#  [params.analytics.bing]
#    SiteVerificationTag = "XYZabc"
#  [params.analytics.yandex]
#    SiteVerificationTag = "XYZabc"

  [params.cover]
    hidden = false
    hiddenInList = true
    hiddenInSingle = false

  [params.editPost]
    URL = "https://github.com/maggionidev/maggionidev.github.io/tree/main/content/"
    Text = " ✏️ Encontrou um erro? Sujira alterações!"
    appendFilePath = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.1
    minMatchCharLength = 0
    limit = 10
    keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  identifier = "posts"
  name = "[ posts ]"
  url = "posts/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "[ search ]"
  url = "/search/"
  weight = 20

[[menu.main]]
  identifier = "categories"
  name = "[ categories ]"
  url = "/categories/"
  weight = 30

# [[menu.main]]
#  identifier = "tags"
#  name = "🏷️ Tags"
#  url = "/tags/"
#  weight = 30

[[menu.main]]
  identifier = "about"
  name = "[ about me ]"
  url = "/about/"
  weight = 40

pygmentsUseClasses = true

[markup]
  [markup.highlight]
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
