backend:
  name: github
  repo: maggionidev/maggionidev.github.io
  branch: main
  auth_type: implicit
  app_id: Ov23li9yfF4DVlUOzIrb
  base_url: https://api.github.com

local_backend: false

media_folder: "static/images"
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/pt-br/posts"
    create: true

    slug: "{{fields.folder}}/{{fields.slug}}"

    fields:

      - { label: "Título", name: "title", widget: "string" }

      - { label: "Slug", name: "slug", widget: "string" }

      - label: "Pasta"
        name: "folder"
        widget: "select"
        default: "dev"
        options:
            - { label: "Dev", value: "dev" }
            - { label: "Linux", value: "linux" }
            - { label: "Windows", value: "windows" }
            - { label: "Blender", value: "blender" }

      - { label: "Descrição (SEO)", name: "description", widget: "string" }

      - { label: "Resumo", name: "summary", widget: "string", required: false }

      - { label: "Tags", name: "tags", widget: "list", required: false }

      - {
          label: "Categorias",
          name: "categories",
          widget: "list",
          required: false,
        }

      - { label: "Keywords", name: "keywords", widget: "list", required: false }

      - {
          label: "Autor",
          name: "author",
          widget: "string",
          default: "Gabriel Maggioni",
        }

      - { label: "Data", name: "date", widget: "datetime" }

      - { label: "Atualizado em", name: "lastmod", widget: "datetime", required: false }

      - {
          label: "Mostrar TOC",
          name: "showToc",
          widget: "boolean",
          default: true,
        }

      - {
          label: "TOC aberto",
          name: "TocOpen",
          widget: "boolean",
          default: false,
        }

      - { label: "Rascunho", name: "draft", widget: "boolean", default: true }

      - { label: "Conteúdo", name: "body", widget: "markdown" }
