backend:
  name: github
  repo: maggionidev/maggionidev.github.io
  branch: main
  usePKCE: true

site_url: https://maggioni.dev

media_folder: static/images
public_folder: /images

collections:

  - name: posts_dev
    label: Posts Dev
    folder: content/pt-br/posts/dev
    create: true
    slug: "{{slug}}"
    fields: &post_fields
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Descrição (SEO)", name: "description", widget: "string" }
      - { label: "Resumo", name: "summary", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Categorias", name: "categories", widget: "list", required: false }
      - { label: "Keywords", name: "keywords", widget: "list", required: false }
      - { label: "Autor", name: "author", widget: "string", default: "Gabriel Maggioni" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Atualizado em", name: "lastmod", widget: "datetime", required: false }
      - { label: "Mostrar TOC", name: "showToc", widget: "boolean", default: true }
      - { label: "TOC aberto", name: "TocOpen", widget: "boolean", default: false }
      - { label: "Rascunho", name: "draft", widget: "boolean", default: true }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: posts_linux
    label: Posts Linux
    folder: content/pt-br/posts/linux
    create: true
    slug: "{{slug}}"
    fields: *post_fields

  - name: posts_windows
    label: Posts Windows
    folder: content/pt-br/posts/windows
    create: true
    slug: "{{slug}}"
    fields: *post_fields

  - name: posts_blender
    label: Posts Blender
    folder: content/pt-br/posts/blender
    create: true
    slug: "{{slug}}"
    fields: *post_fields